language: "en_US"
auctionIntervalTicks: 72000
bidTimeoutTicks: 600
marketPlaySound: true
marketBroadcast: true
# default 120 sec
marketBroadcastCooldown: 120
#offer slots limit
#permission node heh.offer.[group]
marketSlot:
    default: 10
    builder: 15
database:
    provider: sqlite
    connection:
        autoscan: true
        package: cat.nyaa.HamsterEcoHelper.utils.database.tables
        file: HamsterEcoHelper.db