name: HamsterEcoHelper
main: cat.nyaa.heh.HamsterEcoHelper
description: "Economy helper plugin for hamsters."
version: ${version}
depend: [Vault,NyaaCore]
softdepend: [Essentials,LockettePro]
authors: [cyilin, RecursiveG, ReinWD]
website: "https://github.com/NyaaCat/HamsterEcoHelper"
api-version: 1.13
commands:
  hamsterecohelper:
    description: The command for HamsterEcoHelper
    aliases: [heh, h]
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hauc:
    description: The hauc command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hreq:
    description: The hreq command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hbal:
    description: The hbal command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hbid:
    description: The hbid command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hc:
    description: The hc command for HamsterEcoHelper
    aliases: [hcancel]
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hchest:
    description: The hchest command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hm:
    description: The hm command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hpay:
    description: The hpay command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hsell:
    description: The hsell command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hsellto:
    description: The hsellto command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hshop:
    description: The hshop command for HamsterEcoHelper
    aliases: []
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hsearch:
    description: The search command for HamsterEcoHelper
    aliases: [ ]
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hframe:
    description: The frame command for HamsterEcoHelper
    aliases: [ ]
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"
  hstorage:
    description: The storage command for HamsterEcoHelper
    aliases: [ ]
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"

permissions:
  heh.command:
    default: true
    description: base permission for heh plugin
  heh.business.market:
    default: op
    description: market permission
  heh.business.signshop:
    default: op
    description: signshop permission
  heh.business.auction:
    default: op
    description: auction permission
  heh.business.requisition:
    default: op
    description: requisition permission
  heh.business.bid:
    default: op
    description: bid permission
  heh.business.sell:
    default: op
    description: sell permission
  heh.business.sellto:
    default: op
    description: sellto permission
  heh.business.pay:
    default: op
    description: pay permission
  heh.business.cancel:
    default: op
    description: cancel permission
  heh.business.frame:
    default: op
    description: item frame shop permission
  heh.admin.balance:
    default: op
    description: balance admin permission
  heh.admin.remove:
    default: op
    description: remove
  heh.admin.reload:
    default: op
    description: reload
  heh.storage:
    default: true
    description: storage
